<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Point extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new \App\Scope\PointScope());
    }
}
